---
title: GFT web
timezone: America/Sao_Paulo
collections:
  bookmarks:
    title: Bookmarks
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: 'Descrição pendente '
baseurl: 
url: http://agenciagft.github.io
markdown: kramdown
exclude:
- gulpfile.js
- README.md
- desktop.ini
