title: GFT web
description: > 
  Desenvolvimento e gerenciamento de sistemas web. Aplicativos, e-commerce, CMS, ERP, websites e blogs. Entre em contato e faça um orçamento.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://agenciagft.com"

# Build settings
markdown: kramdown

exclude:
  - gulpfile.js
  - README.md
  - desktop.ini

gems:
  - jekyll-coffeescript

collections:
  sections:
    output: false

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
