---
title: GFT web
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: 'Desenvolvimento e gerenciamento de sistemas web. Aplicativos, e-commerce,
  CMS, ERP, websites e blogs. Entre em contato e faça um orçamento.'
baseurl: ''
url: http://agenciagft.com
markdown: kramdown
exclude:
- gulpfile.js
- README.md
- desktop.ini
gems:
- jekyll-coffeescript
