---
title: GFT web
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    permalink: ''
    menu-title: ''
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: 'Desenvolvimento e gerenciamento de sistemas web. Aplicativos, e-commerce,
  CMS, ERP, websites e blogs. Entre em contato e faça um orçamento.

'
baseurl: 
url: http://agenciagft.com
markdown: kramdown
exclude:
- gulpfile.js
- README.md
- desktop.ini
